# Generated by Django 4.0.2 on 2022-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert')], default='Low'),
        ),
    ]
